
DROP TABLE IF EXISTS Media;
DROP TABLE IF EXISTS [Endpoint];

--DROP TABLE IF EXISTS ContactDetailTelecom;
--DROP TABLE IF EXISTS ContactDetail;

--DROP TABLE IF EXISTS AvailableTime
--DROP TABLE IF EXISTS NotAvailable
--DROP TABLE IF EXISTS PractitionerRole

--DROP TABLE IF EXISTS Link;
--DROP TABLE IF EXISTS Contact;
--DROP TABLE IF EXISTS Communication;

--DROP TABLE IF EXISTS UsageContext;

DROP TABLE IF EXISTS [Money];

DROP TABLE IF EXISTS DosageDoseAndRate;
DROP TABLE IF EXISTS DosageDoseAndRate_HT;
DROP TABLE IF EXISTS DosageAdditionalInstruction;
DROP TABLE IF EXISTS Dosage;
DROP TABLE IF EXISTS Ratio;
DROP TABLE IF EXISTS Quantity;

DROP TABLE IF EXISTS [Address];
DROP TABLE IF EXISTS ContactPoint;
DROP TABLE IF EXISTS HumanName;

DROP TABLE IF EXISTS Attachment;
DROP TABLE IF EXISTS Annotation;
DROP TABLE IF EXISTS Uri;
DROP TABLE IF EXISTS Canonical;
DROP TABLE IF EXISTS Identifier;
DROP TABLE IF EXISTS Reference;
DROP TABLE IF EXISTS Coding;
DROP TABLE IF EXISTS CodeableConcept;