DROP TABLE IF EXISTS AdverseEventSuspectEntity_HTCausality;
DROP TABLE IF EXISTS AdverseEventCausality_HT;
DROP TABLE IF EXISTS AdverseEventSuspectEntity;
DROP TABLE IF EXISTS AdverseEventSuspectEntity_HT
DROP TABLE IF EXISTS AdverseEventStudy;
DROP TABLE IF EXISTS AdverseEventReferenceDocument;
DROP TABLE IF EXISTS AdverseEventSubjectMedicalHistory;
DROP TABLE IF EXISTS AdverseEventContributor;
DROP TABLE IF EXISTS AdverseEventResultingCondition;
DROP TABLE IF EXISTS AdverseEventCategory;
DROP TABLE IF EXISTS AdverseEvent;
