DROP TABLE IF EXISTS PersonLink;
DROP TABLE IF EXISTS PersonLink_HT;
DROP TABLE IF EXISTS PersonAddress;
DROP TABLE IF EXISTS PersonTelecom;
DROP TABLE IF EXISTS PersonName;
DROP TABLE IF EXISTS PersonIdentifier;
DROP TABLE IF EXISTS Person;