-- MANGLER HJELPETABELLER?

DROP TABLE IF EXISTS PatientGeneralPractitioner;
DROP TABLE IF EXISTS PatientAttachment;
DROP TABLE IF EXISTS PatientAddress;
DROP TABLE IF EXISTS PatientTelecom;
DROP TABLE IF EXISTS PatientHumanName;
DROP TABLE IF EXISTS PatientIdentifier;
DROP TABLE IF EXISTS Patient;