DROP TABLE IF EXISTS GoalTarget;
DROP TABLE IF EXISTS GoalTarget_HT;

DROP TABLE IF EXISTS GoalOutcomeReference;
DROP TABLE IF EXISTS GoalOutcomeCode;
DROP TABLE IF EXISTS GoalNote;
DROP TABLE IF EXISTS GoalAdresses;
DROP TABLE IF EXISTS GoalCategory;
DROP TABLE IF EXISTS Goal;